// src/App.tsx
import { useCallback, useEffect } from 'react';
import { useMachine } from '@xstate/react';
import { machine } from './machine/machine';
import { type Digit, type MachineEvents } from './machine/type';
import { MachineEventTypes } from './machine/events';
import { type ValueOf } from './types';
import { ArithmeticOperatorMap, COMMANDS, CommandsMap, DIGITS, OPERATORS } from "./common";
import { getKeyboardInputHandler } from './helpers';
import './App.css'

type AppProps = {
  fastForwardEvents?: MachineEvents[],
};

export function App({ fastForwardEvents }: AppProps) {
  const [state, send] = useMachine(machine, { devTools: true });

  useEffect(() => {
    const keyboardInputHandler = getKeyboardInputHandler(send);
    document.addEventListener('keydown', keyboardInputHandler);
    return () => {
      document.removeEventListener('keydown', keyboardInputHandler);
    }
  }, [])


  useEffect(() => {
    if (fastForwardEvents) {
      fastForwardEvents.forEach((event) => {
        send(event);
      });
    }
  }, [fastForwardEvents])

  const renderDigitButton = useCallback((digit: Digit) => <button
    key={digit}
    type="button"
    onClick={() => {
      send({ type: MachineEventTypes.DIGIT_CLICKED, data: digit });
    }}
    data-test={`digit${digit}`}
    disabled={!state.can({
      type: MachineEventTypes.DIGIT_CLICKED,
      data: digit,
    })}
  >
    {digit}
  </button>, [state]);

  const renderOperator = useCallback(({
                                        operator,
                                        displaySign
                                      }: ValueOf<typeof ArithmeticOperatorMap>) => <button
    key={operator}
    type="button"
    onClick={() => {
      send({ type: MachineEventTypes.OPERATOR_CLICKED, data: operator });
    }}
    disabled={!state.can({
      type: MachineEventTypes.OPERATOR_CLICKED, data: operator,
    })}
    data-test={`operator${operator}`}
  >
    {displaySign}
  </button>, [state]);

  const renderCommand = useCallback(({ eventType, displaySign, 'data-test': dataTest }: ValueOf<typeof CommandsMap>) =>
    <button
      key={displaySign}
      type="button"
      onClick={() => {
        send({ type: eventType })
      }}
      disabled={!state.can(eventType)}
      data-test={`command${dataTest}`}
    >
      {displaySign}
    </button>, [state]);

  return (
    <div className="App">
      {state.matches('AlertError') && <div>
        {renderCommand(CommandsMap.OK)}
        <div data-test="error-zero-division" className="error-message">Error: Division by Zero</div>
      </div>}
      <input
        type="text"
        readOnly
        value={
          `${
            state.matches('NegativeNumber1')
              ? '-'
              : ''
          }${
            state.matches({ Cluster: 'Start' })
            || state.matches('NegativeNumber1')
              ? ''
              : state.context.operand1
          }${
            state.matches('OperatorEntered')
            || state.matches('NegativeNumber2')
            || state.matches('Operand2Entered')
            || state.matches('AlertError')
              ? ` ${ArithmeticOperatorMap[state.context.operator].displaySign} `
              : ''
          }${
            state.matches('NegativeNumber2')
              ? '-'
              : ''
          }${
            state.matches('Operand2Entered')
            || state.matches('AlertError')
              ? state.context.operand2
              : ''
          }`
        }
        className="calc-input"
        data-test="calc-input"
      />
      <div className="container">
        <section className="commands-section">{COMMANDS.map(renderCommand)}</section>
        <section className="digits-section">
          {DIGITS.map(renderDigitButton)}
          {renderCommand(CommandsMap.DECIMAL_POINT)}
          {renderCommand(CommandsMap.EQUAL)}
        </section>
        <section className="operators-section">{OPERATORS.map(renderOperator)}</section>
      </div>
    </div>
  )
}

// src/App.vue
<script lang="ts">
import { defineComponent, onMounted, onUnmounted } from 'vue';
import { useMachine } from '@xstate/vue';
import { machine } from './machine/machine';
import { MachineEventTypes } from './machine/events';
import { ArithmeticOperatorMap, COMMANDS, Commands, CommandsMap, DIGITS, OPERATORS } from './common';
import { getKeyboardInputHandler } from './helpers';
import './App.css';

export default defineComponent({
  name: 'App',
  setup() {
    const { state, send } = useMachine(machine, { devTools: true });

    const keyboardInputHandler = getKeyboardInputHandler(send);

    onMounted(() => {
      document.addEventListener('keydown', keyboardInputHandler);
    });
    onUnmounted(() => {
      document.removeEventListener('keydown', keyboardInputHandler);
    });

    return {
      state,
      send,
      ArithmeticOperatorMap,
      MachineEventTypes,
      CommandsMap,
      Commands,
      DIGITS,
      OPERATORS,
      COMMANDS,
    }
  },
})
</script>

<template>
  <div class="App">
    <div v-if="state.matches('AlertError')">
      <button
          type="button"
          data-test="commandOK"
          @click="send({ type: MachineEventTypes.OK_BUTTON_CLICKED })"
          :disabled="!state.can(MachineEventTypes.OK_BUTTON_CLICKED)"
      >
        OK
      </button>
      <div data-test="error-zero-division" class="error-message">Error: Division by Zero</div>
    </div>
    <input type="text" readonly class="calc-input" data-test="calc-input" :value="
          `${
            state.matches('NegativeNumber1')
              ? '-'
              : ''
          }${
            state.matches({ Cluster: 'Start' })
            || state.matches('NegativeNumber1')
              ? ''
              : state.context.operand1
          }${
            state.matches('OperatorEntered')
            || state.matches('NegativeNumber2')
            || state.matches('Operand2Entered')
            || state.matches('AlertError')
              ? ` ${ArithmeticOperatorMap[state.context.operator].displaySign} `
              : ''
          }${
            state.matches('NegativeNumber2')
              ? '-'
              : ''
          }${
            state.matches('Operand2Entered')
            || state.matches('AlertError')
              ? state.context.operand2
              : ''
          }`">
    <div class="container">
      <section class="commands-section">
        <button
            v-for="{ 'data-test': dataTest, eventType, displaySign } in COMMANDS"
            type="button"
            :key="dataTest"
            :data-test="'command' + dataTest"
            @click="send({ type: eventType })"
            :disabled="!state.can({ type: eventType })"
        >
          {{ displaySign }}
        </button>

      </section>
      <section class="digits-section">
        <button
            v-for="digit in DIGITS"
            type="button"
            :key="digit"
            :data-test="'digit' + digit"
            @click="send({ type: MachineEventTypes.DIGIT_CLICKED, data: digit })"
            :disabled="!state.can({ type: MachineEventTypes.DIGIT_CLICKED, data: digit })"
        >
          {{ digit }}
        </button>
        <button
            v-for="{ 'data-test': dataTest, eventType, displaySign } in
            [
              CommandsMap[Commands.DECIMAL_POINT],
              CommandsMap[Commands.EQUAL],
            ]"
            type="button"
            :key="dataTest"
            :data-test="'command' + dataTest"
            @click="send({ type: eventType })"
            :disabled="!state.can({ type: eventType })"
        >
          {{ displaySign }}
        </button>
      </section>
      <section class="operators-section">
        <button
            v-for="({ operator, displaySign }) in OPERATORS"
            type="button"
            :key="operator"
            :data-test="'operator' + operator"
            @click="send({ type: MachineEventTypes.OPERATOR_CLICKED, data: operator })"
            :disabled="!state.can({ type: MachineEventTypes.OPERATOR_CLICKED, data: operator })"
        >
          {{ displaySign }}
        </button>
      </section>
    </div>
  </div>
</template>
